nelmio_api_doc:
  documentation:
    servers:
      - url: https://depps.leadagro.net
    info:
      title: Documentation API Application MyDepps
      description: APIs pour toute la gestion du projet MyDepps
      version: 1.0.0

    # Définir le schéma de sécurité pour Bearer
    components:
      securitySchemes:
        BearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT

    security:
      - BearerAuth: []  # Spécifie que la documentation utilise BearerAuth

  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$)  # Accepts routes under /api except /api/doc
