framework:
    workflows:
        validation_compte:
            type: 'state_machine'
            audit_trail:
              enabled: true
            marking_store:
              type: 'method'
              property: 'status'
            supports:
                - App\Entity\Professionnel
            initial_marking: attente
            places:
                - attente
                - rejete
                - accepte
                - valide
                - refuse
                - renouvellement
                - a_jour
            transitions:
                acceptation:
                    from: attente
                    to: accepte
                rejet:
                    from: attente
                    to: rejete
                refuse:
                    from: accepte
                    to: refuse
                validation:
                    from: accepte 
                    to: valide
                renouvellement:
                    from: valide
                    to: renouvellement
                mis_a_jour:
                    from: renouvellement 
                    to: a_jour

        validation_etablissement:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Etablissement
            initial_marking: dossier_initie
            places:
                - dossier_initie
                - attente_dossier_depot_service_courrier
                - dossier_attente_validation_directrice
                - dossier_valide_directrice
                - dossier_rejete_directrice
                - dossier_imputer
                - dossier_attente_pragramme_visite
                - visite_programmer
                - visite_programmer_conforme
                - visite_programmer_non_conforme_attente_paiement
            transitions:
                depot_service_courrier:
                    from: dossier_initie
                    to: attente_dossier_depot_service_courrier
                
                soumission_validation:
                    from: attente_dossier_depot_service_courrier
                    to: dossier_attente_validation_directrice
                
                validation_directrice:
                    from: dossier_attente_validation_directrice
                    to: dossier_valide_directrice
                
                rejet_directrice:
                    from: dossier_attente_validation_directrice
                    to: dossier_rejete_directrice
                
                imputation_dossier:
                    from: dossier_valide_directrice
                    to: dossier_imputer
                
                attente_programmation_visite:
                    from: dossier_imputer
                    to: dossier_attente_pragramme_visite
                
                programmation_visite:
                    from: dossier_attente_pragramme_visite
                    to: visite_programmer
                
                validation_visite_conforme:
                    from: visite_programmer
                    to: visite_programmer_conforme

                validation_visite_conforme_paiement:
                    from: visite_programmer
                    to: visite_programmer_non_conforme_attente_paiement

                validation_visite_conforme_paiement_soumision:
                    from: visite_programmer_non_conforme_attente_paiement
                    to: attente_dossier_depot_service_courrier