version: '3'

services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - '3000:80'
    volumes:
      - mercure_data:/data
      - mercure_config:/config
      #- K:/PROJET/BACK-END/SYMFONY/KNH/bedoo/mercure/Caddyfile:/etc/caddy/Caddyfile
   # networks:
      #- mynetwork

volumes:
  mercure_data:
  mercure_config:

#networks:
  #mynetwork:
