api_login_check:
    path: /api/login_check_user_front
    methods: ['POST']

api_api_login_check:
    path: /api/auth/login_check_admin
    methods: ['POST']
    
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app.swagger_ui:
    path: /
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
